// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nK16SbD1uHwpGuyRoqAMNN
// Component: n0-tY1aChErG
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_website_starter.module.css"; // plasmic-import: nK16SbD1uHwpGuyRoqAMNN/projectcss
import sty from "./PlasmicCountdownNumber.module.css"; // plasmic-import: n0-tY1aChErG/css

createPlasmicElementProxy;

export const PlasmicCountdownNumber__VariantProps = new Array();

export const PlasmicCountdownNumber__ArgProps = new Array("number", "unit");

const $$ = {};

function PlasmicCountdownNumber__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__x1N2T)}>
        {p.renderPlasmicSlot({
          defaultContents: "42",
          value: args.number,
          className: classNames(sty.slotTargetNumber)
        })}
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__bitDm)}>
        {p.renderPlasmicSlot({
          defaultContents: "Days",
          value: args.unit
        })}
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCountdownNumber__ArgProps,
          internalVariantPropNames: PlasmicCountdownNumber__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCountdownNumber__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCountdownNumber";
  } else {
    func.displayName = `PlasmicCountdownNumber.${nodeName}`;
  }
  return func;
}

export const PlasmicCountdownNumber = Object.assign(
  // Top-level PlasmicCountdownNumber renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicCountdownNumber
    internalVariantProps: PlasmicCountdownNumber__VariantProps,
    internalArgProps: PlasmicCountdownNumber__ArgProps
  }
);

export default PlasmicCountdownNumber;
/* prettier-ignore-end */
