// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nK16SbD1uHwpGuyRoqAMNN
// Component: z3zAS5I9PFXG
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import CountdownNumber from "../../CountdownNumber"; // plasmic-import: n0-tY1aChErG/component
import { Timer } from "@plasmicpkgs/plasmic-basic-components";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_website_starter.module.css"; // plasmic-import: nK16SbD1uHwpGuyRoqAMNN/projectcss
import sty from "./PlasmicCountdown.module.css"; // plasmic-import: z3zAS5I9PFXG/css

createPlasmicElementProxy;

export const PlasmicCountdown__VariantProps = new Array();

export const PlasmicCountdown__ArgProps = new Array("targetTimeUtc");

const $$ = {};

function PlasmicCountdown__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          targetTimeUtc: "2025-12-10T23:26:25.224Z"
        },
        props.args
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "remainingSeconds",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <CountdownNumber
          className={classNames("__wab_instance", sty.countdownNumber___1YbQg)}
          number={
            <React.Fragment>
              {(() => {
                try {
                  return Math.floor($state.remainingSeconds / 60 / 60 / 24);
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "42";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          }
          unit={"Days"}
        />

        <CountdownNumber
          className={classNames("__wab_instance", sty.countdownNumber__lmOw4)}
          number={
            <React.Fragment>
              {(() => {
                try {
                  return Math.floor($state.remainingSeconds / 60 / 60) % 24;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "42";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          }
          unit={"Hours"}
        />

        <CountdownNumber
          className={classNames("__wab_instance", sty.countdownNumber__sePxn)}
          number={
            <React.Fragment>
              {(() => {
                try {
                  return Math.floor($state.remainingSeconds / 60) % 60;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "42";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          }
          unit={"Minutes"}
        />

        <CountdownNumber
          className={classNames("__wab_instance", sty.countdownNumber__lRaP4)}
          number={
            <React.Fragment>
              {(() => {
                try {
                  return $state.remainingSeconds % 60;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "42";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          }
          unit={"Seconds"}
        />
      </p.Stack>
      <Timer
        data-plasmic-name={"timer"}
        data-plasmic-override={overrides.timer}
        className={classNames("__wab_instance", sty.timer)}
        intervalSeconds={1}
        isRunning={true}
        onTick={async () => {
          const $steps = {};
          $steps["updateRemainingSeconds"] = true
            ? (() => {
                const actionArgs = {
                  variable: {
                    objRoot: $state,
                    variablePath: ["remainingSeconds"]
                  },
                  operation: 0,
                  value: Math.floor(
                    (new Date($props.targetTimeUtc).getTime() -
                      new Date().getTime()) /
                      1000
                  )
                };
                return (({ variable, value, startIndex, deleteCount }) => {
                  if (!variable) {
                    return;
                  }
                  const { objRoot, variablePath } = variable;
                  p.set(objRoot, variablePath, value);
                  return value;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateRemainingSeconds"] != null &&
            typeof $steps["updateRemainingSeconds"] === "object" &&
            typeof $steps["updateRemainingSeconds"].then === "function"
          ) {
            $steps["updateRemainingSeconds"] = await $steps[
              "updateRemainingSeconds"
            ];
          }
        }}
        runWhileEditing={true}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "timer"],
  freeBox: ["freeBox"],
  timer: ["timer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCountdown__ArgProps,
          internalVariantPropNames: PlasmicCountdown__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCountdown__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCountdown";
  } else {
    func.displayName = `PlasmicCountdown.${nodeName}`;
  }
  return func;
}

export const PlasmicCountdown = Object.assign(
  // Top-level PlasmicCountdown renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    timer: makeNodeComponent("timer"),
    // Metadata about props expected for PlasmicCountdown
    internalVariantProps: PlasmicCountdown__VariantProps,
    internalArgProps: PlasmicCountdown__ArgProps
  }
);

export default PlasmicCountdown;
/* prettier-ignore-end */
